import React, { useEffect, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Animated,
  Linking,
  Platform,
  SafeAreaView,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import Svg, { Circle, Defs, LinearGradient as SvgLinearGradient, Stop } from 'react-native-svg';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import {
  CircleDollarSign,
  Crown,
  FileEdit,
  FileQuestion,
  FileText,
  LucideIcon,
  Search,
  Sparkles,
} from 'lucide-react-native';

import { API_BASE_URL, getAnalysis } from '../services/api';
import type { AgentReport, ReportData, Verdict } from '../services/types';
import { findingColor } from '../services/types';
import { useReports } from '../context/ReportsContext';

// ─── design tokens (mirrors app/index.tsx + how-they-work.tsx) ─────────────
const T = {
  bg: '#08080d',
  ink: '#ffffff',
  dim: 'rgba(255,255,255,0.56)',
  faint: 'rgba(255,255,255,0.36)',
  ghost: 'rgba(255,255,255,0.22)',
  line: 'rgba(255,255,255,0.07)',
  line2: 'rgba(255,255,255,0.12)',
  glass: 'rgba(255,255,255,0.035)',
  purple: '#9550ee',
  purpleSoft: 'rgba(149,80,238,0.18)',
  purpleEdge: 'rgba(149,80,238,0.45)',
  purpleInk: '#d6c0ff',
  green: '#3ddc97',
  amber: '#f0b34a',
  red: '#ff5d6c',
};
const MONO = Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }) as string;

// ─── placeholder report (used when navigated without an id) ────────────────
const PLACEHOLDER_REPORT: ReportData = {
  startup_name: 'Bykea',
  intent: 'invest',
  tags: ['Mobility', 'Series A', 'Karachi', 'B2C'],
  score: 712,
  verdict: 'INVEST',
  verdict_sub: 'WITH CONDITIONS',
  dimensions: [
    { name: 'Market fit', score: 78 },
    { name: 'Financials', score: 63 },
    { name: 'Brand power', score: 81 },
    { name: 'Strategy', score: 70 },
  ],
  metrics: [
    { label: 'Est. valuation', value: '$28M', change: '+12% YoY', change_type: 'positive' },
    { label: 'Monthly GMV', value: '₨ 2.4B', change: 'Growing', change_type: 'positive' },
    { label: 'Burn rate / mo', value: '$180K', change: 'High risk', change_type: 'negative' },
    { label: 'Runway est.', value: '14 mo', change: 'Watch', change_type: 'warning' },
  ],
  agent_reports: [],
};

// ─── verdict pill mapping ──────────────────────────────────────────────────
const VERDICT_TONE: Record<Verdict, { bg: string; border: string; ink: string }> = {
  INVEST:  { bg: 'rgba(61,220,151,0.12)',  border: 'rgba(61,220,151,0.45)',  ink: T.green },
  WATCH:   { bg: 'rgba(240,179,74,0.12)',  border: 'rgba(240,179,74,0.45)',  ink: T.amber },
  PASS:    { bg: 'rgba(255,93,108,0.10)',  border: 'rgba(255,93,108,0.40)',  ink: T.red },
  ACQUIRE: { bg: 'rgba(149,80,238,0.14)',  border: 'rgba(149,80,238,0.55)',  ink: T.purpleInk },
};

// ─── agent icon mapping (matches app/loading.tsx + how-they-work.tsx) ──────
const AGENT_META: Record<number, { Icon: LucideIcon; color: string }> = {
  1: { Icon: Search,           color: '#FF6B6B' },
  2: { Icon: CircleDollarSign, color: '#D4FF3D' },
  3: { Icon: Sparkles,         color: '#A78BFA' },
  4: { Icon: Crown,            color: '#FFC83C' },
};

// ─── deliverables (auto-generated by the CVO) ──────────────────────────────
const DELIVERABLES: { key: string; icon: LucideIcon; title: string; sub: string; color: string }[] = [
  { key: 'brief',     icon: FileText,     title: 'Investor Brief',    sub: '2-page PDF · tl;dr + appendix',  color: T.purple },
  { key: 'questions', icon: FileQuestion, title: 'Questions to Ask',  sub: '12 sharp questions for the founder', color: T.purpleInk },
  { key: 'memo',      icon: FileEdit,     title: 'Deal Memo Draft',   sub: 'Editable doc · 800 words',          color: T.amber },
];

// ─── PDF builder (used by the save button) ─────────────────────────────────
const HTML_ESC: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};
const esc = (s: string): string => s.replace(/[&<>"']/g, (c) => HTML_ESC[c] ?? c);

function buildReportHtml(report: ReportData, displayName: string): string {
  const verdictLabel = report.verdict === 'PASS' ? 'REJECTED' : report.verdict;
  const subText = report.verdict_sub ? ` · ${esc(report.verdict_sub)}` : '';

  const verdictClassMap: Record<string, string> = {
    INVEST: 'inv',
    PASS: 'pass',
    WATCH: 'watch',
    PIVOT: 'watch',
    ACQUIRE: 'acq',
  };
  const verdictClass = verdictClassMap[report.verdict] ?? 'watch';

  const tagsHtml = report.tags
    .slice(0, 6)
    .map((t) => `<span class="tag">${esc(t)}</span>`)
    .join('');

  const dimsHtml = report.dimensions
    .map((d) => {
      const pct = Math.max(0, Math.min(100, d.score));
      return `<div class="dim">
        <span class="dim-name">${esc(d.name)}</span>
        <span class="dim-track"><span class="dim-fill" style="width:${pct}%"></span></span>
        <span class="dim-score">${d.score}</span>
      </div>`;
    })
    .join('');

  const metricsHtml = report.metrics
    .map((m) => {
      const tone =
        m.change_type === 'positive'
          ? '#1e8c5f'
          : m.change_type === 'negative'
          ? '#c33646'
          : m.change_type === 'warning'
          ? '#b07410'
          : '#6b6478';
      return `<div class="metric">
        <div class="metric-label">${esc(m.label.toUpperCase())}</div>
        <div class="metric-value">${esc(m.value)}</div>
        <div class="metric-change" style="color:${tone}">${esc(m.change)}</div>
      </div>`;
    })
    .join('');

  const agentsHtml =
    report.agent_reports.length === 0
      ? '<p class="muted">No agent reports surfaced for this run.</p>'
      : report.agent_reports
          .map((a) => {
            const findings =
              a.findings.length > 0
                ? `<ul class="findings">${a.findings
                    .map((f) => `<li>${esc(f.text)}</li>`)
                    .join('')}</ul>`
                : '';
            return `<div class="agent">
              <div class="agent-head">
                <span class="agent-name">${esc(a.name)}</span>
                <span class="agent-role">${esc(a.role.toUpperCase())}</span>
              </div>
              <p class="agent-body">${esc(a.body)}</p>
              ${findings}
            </div>`;
          })
          .join('');

  const date = new Date().toLocaleDateString('en-GB', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(displayName)} — Aura Report</title>
<style>
  *{box-sizing:border-box}
  body{font-family:-apple-system,BlinkMacSystemFont,"Inter",Helvetica,Arial,sans-serif;background:#fff;color:#15121f;margin:0;padding:40px;line-height:1.5}
  .brand{font-size:10.5px;letter-spacing:2px;color:#9550ee;font-weight:700;margin-bottom:6px;font-family:"SF Mono",Menlo,monospace}
  .header{border-bottom:2px solid #9550ee;padding-bottom:14px;margin-bottom:22px}
  .startup{font-size:28px;font-weight:700;letter-spacing:-0.5px}
  .tags{margin-top:8px}
  .tag{display:inline-block;padding:3px 9px;border-radius:999px;background:#f4f0ff;color:#7b3bd9;font-size:10px;font-weight:500;margin-right:4px;margin-bottom:4px}
  .score-block{margin:22px 0;padding:24px;background:#f8f6ff;border-radius:16px;border:1px solid #e5dffa;text-align:center}
  .eyebrow{font-family:"SF Mono",Menlo,monospace;font-size:9px;letter-spacing:1.4px;color:#6b6478;font-weight:600}
  .score-num{font-size:60px;font-weight:600;color:#15121f;letter-spacing:-2px;line-height:1;margin-top:6px}
  .score-max{font-size:14px;color:#6b6478;margin-left:4px}
  .pill{display:inline-block;margin-top:12px;padding:6px 14px;border-radius:8px;border:1px solid;font-size:11px;font-weight:700;letter-spacing:1.2px;font-family:"SF Mono",Menlo,monospace}
  .pill.inv{color:#1e8c5f;background:#e8faf1;border-color:#b5e6cf}
  .pill.pass{color:#c33646;background:#fdebee;border-color:#f4c5cd}
  .pill.watch{color:#b07410;background:#fef4e3;border-color:#f4dcb0}
  .pill.acq{color:#7b3bd9;background:#f4f0ff;border-color:#d8c5fc}
  h2{font-family:"SF Mono",Menlo,monospace;font-size:9.5px;letter-spacing:1.4px;color:#6b6478;font-weight:600;margin:28px 0 12px;text-transform:uppercase}
  .dim{display:flex;align-items:center;gap:12px;margin-bottom:10px}
  .dim-name{flex:0 0 110px;font-size:12px;color:#4a4555;font-weight:500}
  .dim-track{flex:1;height:6px;background:#ece8f4;border-radius:4px;overflow:hidden}
  .dim-fill{display:block;height:100%;background:#9550ee;border-radius:4px}
  .dim-score{flex:0 0 32px;text-align:right;font-size:12px;font-weight:600;font-family:"SF Mono",Menlo,monospace}
  .metrics{display:grid;grid-template-columns:1fr 1fr;gap:10px}
  .metric{background:#f8f6ff;border:1px solid #ece8f4;border-radius:12px;padding:12px}
  .metric-label{font-family:"SF Mono",Menlo,monospace;font-size:9.5px;color:#6b6478;letter-spacing:1.2px;font-weight:600;margin-bottom:6px}
  .metric-value{font-size:18px;font-weight:700;color:#15121f}
  .metric-change{font-family:"SF Mono",Menlo,monospace;font-size:11px;margin-top:4px;letter-spacing:0.4px}
  .agent{margin-bottom:14px;padding:14px;background:#fafafa;border:1px solid #ece8f4;border-radius:12px}
  .agent-head{margin-bottom:8px}
  .agent-name{font-size:13.5px;font-weight:600;color:#15121f}
  .agent-role{font-family:"SF Mono",Menlo,monospace;font-size:10px;color:#6b6478;letter-spacing:1.2px;margin-left:6px}
  .agent-body{font-size:12.5px;color:#4a4555;margin:6px 0}
  .findings{margin:8px 0 0;padding-left:18px}
  .findings li{font-size:12px;color:#4a4555;margin-bottom:3px}
  .muted{color:#6b6478;font-size:12px}
  .footer{margin-top:38px;padding-top:14px;border-top:1px solid #ece8f4;text-align:center;color:#6b6478;font-size:10px;letter-spacing:0.4px;font-family:"SF Mono",Menlo,monospace}
</style></head>
<body>
  <div class="header">
    <div class="brand">◢ VIBEINVEST · AURA REPORT</div>
    <div class="startup">${esc(displayName)}</div>
    ${tagsHtml ? `<div class="tags">${tagsHtml}</div>` : ''}
  </div>

  <div class="score-block">
    <div class="eyebrow">◢ AURA SCORE</div>
    <div><span class="score-num">${report.score}</span><span class="score-max">/ 1000</span></div>
    <div><span class="pill ${verdictClass}">${esc(verdictLabel)}${subText}</span></div>
  </div>

  <h2>◢ Dimensions</h2>
  ${dimsHtml}

  <h2>◢ Key metrics</h2>
  <div class="metrics">${metricsHtml || '<p class="muted">No metrics surfaced.</p>'}</div>

  <h2>◢ Agent reports</h2>
  ${agentsHtml}

  <div class="footer">Generated ${esc(date)} · VibeInvest</div>
</body></html>`;
}

function buildBullets(report: ReportData, key: string): string[] {
  if (key === 'brief') {
    return [
      `Aura Score: ${report.score} / 1000`,
      `Verdict: ${report.verdict}${report.verdict_sub ? ` · ${report.verdict_sub}` : ''}`,
      report.tags[0] ? `Sector: ${report.tags[0]}` : 'Sector: —',
      `Dimensions: ${report.dimensions.map((d) => `${d.name} ${d.score}`).join(' · ')}`,
    ];
  }
  if (key === 'questions') {
    const negatives = report.agent_reports
      .flatMap((r) => r.findings)
      .filter((f) => f.type === 'negative' || f.type === 'warning')
      .slice(0, 4)
      .map((f) => f.text);
    return negatives.length ? negatives : ['Margin path?', 'Unit econ at scale?', 'Cash runway?'];
  }
  return [
    `Thesis · ${report.verdict.toLowerCase()} · ${report.startup_name}`,
    `Market · ${report.tags[0] || 'unknown'}`,
    `Risks · ${report.agent_reports
      .flatMap((r) => r.findings)
      .filter((f) => f.type !== 'positive')
      .slice(0, 2)
      .map((f) => f.text.slice(0, 40))
      .join('; ') || 'see findings'}`,
    `Recommendation · ${report.verdict}${report.verdict_sub ? ` · ${report.verdict_sub}` : ''}`,
  ];
}

// ─── small reusable: section header ────────────────────────────────────────
function SectionHead({ eyebrow, title, meta }: { eyebrow: string; title: string; meta?: React.ReactNode }) {
  return (
    <View style={s.sectionHead}>
      <View>
        <Text style={s.eyebrow}>{eyebrow}</Text>
        <Text style={s.sectionTitle}>{title}</Text>
      </View>
      {meta}
    </View>
  );
}

// ─── verdict pill ──────────────────────────────────────────────────────────
function VerdictPill({ verdict, sub }: { verdict: Verdict; sub?: string }) {
  const m = VERDICT_TONE[verdict] ?? VERDICT_TONE.WATCH;
  const label = verdict === 'PASS' ? 'REJECTED' : verdict;
  return (
    <View style={[s.verdictPill, { backgroundColor: m.bg, borderColor: m.border }]}>
      <View style={[s.verdictDot, { backgroundColor: m.ink }]} />
      <Text style={[s.verdictPillText, { color: m.ink }]}>{label}</Text>
      {sub && <Text style={[s.verdictPillSub, { color: m.ink }]}> · {sub}</Text>}
    </View>
  );
}

// ─── aura ring (svg) ───────────────────────────────────────────────────────
function AuraRing({ score, max = 1000, size = 168 }: { score: number; max?: number; size?: number }) {
  const r = (size - 20) / 2;
  const C0 = 2 * Math.PI * r;
  const pct = Math.max(0, Math.min(1, score / max));
  const offset = C0 * (1 - pct);
  return (
    <Svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
      <Defs>
        <SvgLinearGradient id="auraRingReport" x1="0" y1="0" x2="1" y2="1">
          <Stop offset="0%" stopColor="#c79bff" />
          <Stop offset="50%" stopColor="#9550ee" />
          <Stop offset="100%" stopColor="#5b2ea3" />
        </SvgLinearGradient>
      </Defs>
      <Circle cx={size / 2} cy={size / 2} r={r} stroke="rgba(255,255,255,0.06)" strokeWidth={6} fill="none" />
      {score > 0 && (
        <Circle
          cx={size / 2}
          cy={size / 2}
          r={r}
          stroke="url(#auraRingReport)"
          strokeWidth={6}
          fill="none"
          strokeLinecap="round"
          strokeDasharray={C0}
          strokeDashoffset={offset}
          transform={`rotate(-90 ${size / 2} ${size / 2})`}
        />
      )}
    </Svg>
  );
}

// ─── dimension bar ─────────────────────────────────────────────────────────
function DimBar({ name, score }: { name: string; score: number }) {
  return (
    <View style={s.dimRow}>
      <Text style={s.dimName} numberOfLines={1}>{name}</Text>
      <View style={s.dimTrack}>
        <View style={[s.dimFill, { width: `${Math.max(0, Math.min(100, score))}%` }]} />
      </View>
      <Text style={s.dimScore}>{score}</Text>
    </View>
  );
}

// ─── metric card (2-up grid) ───────────────────────────────────────────────
function MetricCard({ label, value, change, changeColor }: { label: string; value: string; change: string; changeColor: string }) {
  return (
    <View style={s.metricOuter}>
      <LinearGradient
        colors={['rgba(255,255,255,0.045)', 'rgba(255,255,255,0.012)']}
        start={{ x: 0, y: 0 }}
        end={{ x: 0, y: 1 }}
        style={s.metric}
      >
        <Text style={s.metricLabel}>{label.toUpperCase()}</Text>
        <Text style={s.metricValue}>{value}</Text>
        <Text style={[s.metricChange, { color: changeColor }]}>{change}</Text>
      </LinearGradient>
    </View>
  );
}

// ─── agent report card (expandable) ────────────────────────────────────────
function AgentCard({
  agentId,
  name,
  role,
  badge,
  body,
  findings,
  expanded,
  onToggle,
}: {
  agentId: number;
  name: string;
  role: string;
  badge: string;
  body: string;
  findings: { text: string; color: string }[];
  expanded: boolean;
  onToggle: () => void;
}) {
  const meta = AGENT_META[agentId] ?? AGENT_META[1];
  return (
    <View style={s.agentCardOuter}>
      <TouchableOpacity onPress={onToggle} activeOpacity={0.85}>
        <LinearGradient
          colors={
            expanded
              ? ['rgba(149,80,238,0.10)', 'rgba(149,80,238,0.02)']
              : ['rgba(255,255,255,0.045)', 'rgba(255,255,255,0.012)']
          }
          start={{ x: 0, y: 0 }}
          end={{ x: 0, y: 1 }}
          style={s.agentCard}
        >
          <View style={s.agentHeader}>
            <View
              style={[
                s.agentIconBubble,
                { backgroundColor: `${meta.color}1f`, borderColor: `${meta.color}55` },
              ]}
            >
              <meta.Icon size={18} color={meta.color} />
            </View>
            <View style={{ flex: 1, minWidth: 0 }}>
              <Text style={s.agentName}>{name}</Text>
              <Text style={s.agentRole}>{role.toUpperCase()}</Text>
            </View>
            <View
              style={[
                s.agentBadge,
                { backgroundColor: `${meta.color}1f`, borderColor: `${meta.color}55` },
              ]}
            >
              <Text style={[s.agentBadgeText, { color: meta.color }]}>{badge}</Text>
            </View>
            <Ionicons
              name={expanded ? 'chevron-up' : 'chevron-down'}
              size={14}
              color={T.faint}
              style={{ marginLeft: 8 }}
            />
          </View>

          {expanded && (
            <View style={s.agentBody}>
              <Text style={s.agentBodyText}>{body}</Text>
              {findings.length > 0 && (
                <View style={s.findingsList}>
                  {findings.map((f, i) => (
                    <View key={i} style={s.findingRow}>
                      <View style={[s.findingDot, { backgroundColor: f.color }]} />
                      <Text style={s.findingText}>{f.text}</Text>
                    </View>
                  ))}
                </View>
              )}
            </View>
          )}
        </LinearGradient>
      </TouchableOpacity>
    </View>
  );
}

// ─── deliverable card (expandable) ─────────────────────────────────────────
function DeliverableItem({
  item,
  bullets,
  expanded,
  onToggle,
}: {
  item: (typeof DELIVERABLES)[number];
  bullets: string[];
  expanded: boolean;
  onToggle: () => void;
}) {
  const Icon = item.icon;
  return (
    <View style={s.delivOuter}>
      <TouchableOpacity onPress={onToggle} activeOpacity={0.85}>
        <LinearGradient
          colors={['rgba(255,255,255,0.045)', 'rgba(255,255,255,0.012)']}
          start={{ x: 0, y: 0 }}
          end={{ x: 0, y: 1 }}
          style={[s.deliv, { borderLeftWidth: 3, borderLeftColor: item.color }]}
        >
          <View style={s.delivHead}>
            <View
              style={[
                s.delivIconBubble,
                { backgroundColor: `${item.color}1f`, borderColor: `${item.color}55` },
              ]}
            >
              <Icon size={18} color={item.color} />
            </View>
            <View style={{ flex: 1, minWidth: 0 }}>
              <Text style={s.delivTitle}>{item.title}</Text>
              <Text style={s.delivSub}>{item.sub}</Text>
            </View>
            <Ionicons
              name={expanded ? 'remove' : 'add'}
              size={18}
              color={T.faint}
              style={{ marginLeft: 8 }}
            />
          </View>

          {expanded && (
            <View style={s.delivBody}>
              {bullets.map((b, i) => (
                <View key={i} style={s.delivBulletRow}>
                  <Text style={s.delivNum}>{(i + 1).toString().padStart(2, '0')}</Text>
                  <Text style={s.delivBulletText}>{b}</Text>
                </View>
              ))}
            </View>
          )}
        </LinearGradient>
      </TouchableOpacity>
    </View>
  );
}

// ─── main screen ───────────────────────────────────────────────────────────
export default function ReportScreen() {
  const router = useRouter();
  const { name, id } = useLocalSearchParams<{ name: string; id?: string }>();

  const [report, setReport] = useState<ReportData | null>(id ? null : PLACEHOLDER_REPORT);
  const [loadError, setLoadError] = useState<string | null>(null);

  // Save to dashboard's in-memory store on first load — guarded so the recent
  // list doesn't duplicate if the screen re-renders.
  const { addReport } = useReports();
  const savedRef = useRef(false);
  useEffect(() => {
    if (!report || savedRef.current) return;
    savedRef.current = true;
    const dims = report.dimensions.slice(0, 3).map((d) => ({ label: d.name, val: d.score }));
    addReport({
      name: report.startup_name,
      score: report.score,
      verdict: report.verdict,
      breakdowns: dims,
    });
  }, [report, addReport]);

  // Load real analysis when an id is passed.
  useEffect(() => {
    if (!id) return;
    let cancelled = false;
    getAnalysis(id)
      .then((a) => {
        if (cancelled) return;
        if (a.report) setReport(a.report);
        else if (a.status === 'failed') {
          setLoadError(a.error || 'Analysis failed.');
          setReport(PLACEHOLDER_REPORT);
        } else {
          setReport(PLACEHOLDER_REPORT);
        }
      })
      .catch((e) => {
        if (cancelled) return;
        setLoadError(e?.message || 'Could not load report.');
        setReport(PLACEHOLDER_REPORT);
      });
    return () => {
      cancelled = true;
    };
  }, [id]);

  // Animated score countup (0 → target over 1500ms with eased curve).
  const target = report?.score ?? 0;
  const startupName = report?.startup_name || name || 'Bykea';
  const [score, setScore] = useState(0);

  useEffect(() => {
    if (!report) return;
    const duration = 1500;
    const startTime = Date.now();
    let rafId: number;
    const animateScore = () => {
      const now = Date.now();
      const progress = Math.min((now - startTime) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      setScore(Math.round(eased * target));
      if (progress < 1) {
        rafId = requestAnimationFrame(animateScore);
      }
    };
    rafId = requestAnimationFrame(animateScore);
    return () => cancelAnimationFrame(rafId);
  }, [report, target]);

  // Expand/collapse state — first item open by default.
  const [expandedAgent, setExpandedAgent] = useState<number | null>(1);
  const [expandedDeliv, setExpandedDeliv] = useState<string | null>('brief');

  // Generate the PDF locally on-device (no backend round-trip needed) and
  // open the native share sheet so the user can save it to Files / Drive /
  // mail / WhatsApp. Works offline and on placeholder reports too.
  const handleDownloadPdf = async () => {
    if (!report) return;
    try {
      const html = buildReportHtml(report, startupName);
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, {
          UTI: 'com.adobe.pdf',
          mimeType: 'application/pdf',
          dialogTitle: `${startupName} — Aura Report`,
        });
      } else {
        // Web / unsupported platform — fall back to opening the local URI.
        Linking.openURL(uri).catch(() => {
          Alert.alert('Saved', `PDF saved at:\n${uri}`);
        });
      }
    } catch (err) {
      Alert.alert(
        'Save failed',
        err instanceof Error ? err.message : 'Could not generate the PDF.',
      );
    }
  };

  const handleShare = async () => {
    if (!id) return;
    const pdfUrl = `${API_BASE_URL}/api/analyses/${id}/pdf`;
    if (Platform.OS === 'web') {
      try {
        if (navigator.clipboard) {
          await navigator.clipboard.writeText(pdfUrl);
          Alert.alert('Link Copied', 'The PDF report link has been copied to your clipboard.');
          return;
        }
      } catch {
        // fall through
      }
    }
    try {
      await Share.share({
        message: `VibeInvest due diligence for ${startupName}: ${pdfUrl}`,
        url: pdfUrl,
        title: `${startupName} Due Diligence Report`,
      });
    } catch {
      Alert.alert('Share Failed', 'Could not share the due diligence report.');
    }
  };

  if (!report) {
    return (
      <SafeAreaView style={[s.screen, { alignItems: 'center', justifyContent: 'center' }]}>
        <ActivityIndicator color={T.purple} />
        <Text style={s.loadingText}>loading report…</Text>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={s.screen}>
      {/* ── header ── */}
      <View style={s.header}>
        <TouchableOpacity
          onPress={() => router.back()}
          style={s.headerBtn}
          accessibilityLabel="Back"
          hitSlop={10}
        >
          <Ionicons name="chevron-back" size={22} color={T.ink} />
        </TouchableOpacity>
        <Text style={s.headerTitle}>Report</Text>
        <View style={s.headerActions}>
          <TouchableOpacity
            onPress={handleShare}
            style={s.headerBtn}
            accessibilityLabel="Share report"
            hitSlop={10}
          >
            <Ionicons name="share-outline" size={20} color={T.ink} />
          </TouchableOpacity>
          <TouchableOpacity
            onPress={handleDownloadPdf}
            style={s.headerBtn}
            accessibilityLabel="Save report as PDF"
            hitSlop={10}
          >
            <Ionicons name="save-outline" size={20} color={T.ink} />
          </TouchableOpacity>
        </View>
      </View>

      <ScrollView contentContainerStyle={{ paddingBottom: 36 }} showsVerticalScrollIndicator={false}>
        {/* ── hero (aura score + verdict) ── */}
        <View style={{ paddingHorizontal: 20, marginTop: 14 }}>
          <View style={s.heroOuter}>
            <LinearGradient
              colors={['rgba(40,24,72,0.65)', 'rgba(14,11,24,0.85)']}
              locations={[0, 0.6]}
              start={{ x: 0.3, y: 0 }}
              end={{ x: 0.7, y: 1 }}
              style={s.hero}
            >
              <Text style={s.eyebrow}>◢ AURA SCORE · FINAL</Text>
              <Text style={s.startupName}>{startupName}</Text>

              <View style={s.heroRingWrap}>
                <AuraRing score={score} size={184} />
                <View style={s.heroRingCenter} pointerEvents="none">
                  <Text style={s.bigScore}>{score}</Text>
                  <Text style={s.scoreMax}>/ 1000</Text>
                </View>
              </View>

              <VerdictPill verdict={report.verdict} sub={report.verdict_sub ?? undefined} />

              {/* tags */}
              {report.tags.length > 0 && (
                <View style={s.tagsRow}>
                  {report.tags.slice(0, 5).map((t, i) => (
                    <View key={`${t}-${i}`} style={s.tag}>
                      <Text style={s.tagText}>{t}</Text>
                    </View>
                  ))}
                </View>
              )}

              <View style={s.heroFootRow}>
                <Text style={s.heroFootText}>⌁ Confidence 0.91 · 4/4 agents</Text>
              </View>
            </LinearGradient>
          </View>

          {loadError && (
            <Text style={s.loadErrorText}>showing placeholder · {loadError}</Text>
          )}
        </View>

        {/* ── dimensions ── */}
        <View style={s.section}>
          <SectionHead eyebrow="◢ DIMENSIONS" title="Score breakdown" />
          <View style={{ gap: 12 }}>
            {report.dimensions.map((d) => (
              <DimBar key={d.name} name={d.name} score={d.score} />
            ))}
          </View>
        </View>

        {/* ── key metrics ── */}
        <View style={s.section}>
          <SectionHead eyebrow="◢ KEY METRICS" title="By the numbers" />
          {report.metrics.length === 0 ? (
            <Text style={s.emptyText}>No metrics surfaced.</Text>
          ) : (
            <View style={s.metricsGrid}>
              {report.metrics.map((m, i) => (
                <MetricCard
                  key={`${m.label}-${i}`}
                  label={m.label}
                  value={m.value}
                  change={m.change}
                  changeColor={findingColor(m.change_type)}
                />
              ))}
            </View>
          )}
        </View>

        {/* ── agent reports ── */}
        <View style={s.section}>
          <SectionHead eyebrow="◢ AGENT REPORTS" title="What each agent found" />
          {report.agent_reports.length === 0 ? (
            <Text style={s.emptyText}>No agent reports yet.</Text>
          ) : (
            <View style={{ gap: 10 }}>
              {report.agent_reports.map((r: AgentReport) => (
                <AgentCard
                  key={r.id}
                  agentId={r.id}
                  name={r.name}
                  role={r.role}
                  badge={r.badge || '—'}
                  body={r.body}
                  findings={r.findings.map((f) => ({ text: f.text, color: findingColor(f.type) }))}
                  expanded={expandedAgent === r.id}
                  onToggle={() => setExpandedAgent(expandedAgent === r.id ? null : r.id)}
                />
              ))}
            </View>
          )}
        </View>

        {/* ── deliverables ── */}
        <View style={s.section}>
          <SectionHead
            eyebrow="◢ DELIVERABLES"
            title="Generate"
            meta={
              <View style={s.cvoAutoRow}>
                <Sparkles size={11} color={T.purple} style={{ marginRight: 4 }} />
                <Text style={s.cvoAuto}>CVO AUTO-GENERATED</Text>
              </View>
            }
          />
          <View style={{ gap: 10 }}>
            {DELIVERABLES.map((item) => (
              <DeliverableItem
                key={item.key}
                item={item}
                bullets={buildBullets(report, item.key)}
                expanded={expandedDeliv === item.key}
                onToggle={() => setExpandedDeliv(expandedDeliv === item.key ? null : item.key)}
              />
            ))}
          </View>
        </View>

        {/* ── CTA ── */}
        <View style={{ paddingHorizontal: 20, marginTop: 28 }}>
          <TouchableOpacity
            onPress={() => router.push('/')}
            accessibilityLabel="Start a new analysis"
            activeOpacity={0.85}
            style={s.ctaTouchable}
          >
            <LinearGradient
              colors={['#9550ee', '#7b3bd9']}
              start={{ x: 0, y: 0 }}
              end={{ x: 0, y: 1 }}
              style={s.cta}
            >
              <Text style={s.ctaText}>New Analysis</Text>
              <Ionicons name="arrow-forward" size={16} color="#fff" style={{ marginLeft: 8 }} />
            </LinearGradient>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

// ─── styles ────────────────────────────────────────────────────────────────
const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: T.bg },
  loadingText: { color: T.faint, marginTop: 12, fontSize: 12, letterSpacing: 0.6 },

  // header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: T.line,
  },
  headerBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: T.ink,
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: -0.2,
  },
  headerActions: { flexDirection: 'row', alignItems: 'center' },

  // section header
  sectionHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 12,
  },
  eyebrow: {
    fontFamily: MONO,
    fontSize: 9.5,
    color: T.faint,
    letterSpacing: 1.4,
    marginBottom: 3,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: T.ink,
    letterSpacing: -0.3,
  },

  // section wrapper
  section: { paddingHorizontal: 20, marginTop: 26 },
  emptyText: { color: T.ghost, fontSize: 12 },

  // ── hero ────────────────────────────────────────────────────────────────
  heroOuter: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.purpleEdge,
    overflow: 'hidden',
    shadowColor: T.purple,
    shadowOpacity: 0.2,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  hero: {
    padding: 22,
    alignItems: 'center',
  },
  startupName: {
    fontSize: 22,
    fontWeight: '600',
    color: T.ink,
    letterSpacing: -0.4,
    marginTop: 4,
    marginBottom: 10,
    textAlign: 'center',
  },
  heroRingWrap: {
    width: 184,
    height: 184,
    position: 'relative',
    marginBottom: 16,
  },
  heroRingCenter: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bigScore: {
    fontSize: 58,
    fontWeight: '500',
    color: T.ink,
    letterSpacing: -2,
    lineHeight: 60,
  },
  scoreMax: {
    fontFamily: MONO,
    fontSize: 11,
    color: T.faint,
    letterSpacing: 0.8,
    marginTop: 4,
  },

  // tags
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'center',
    marginTop: 14,
  },
  tag: {
    paddingVertical: 3,
    paddingHorizontal: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.line2,
  },
  tagText: {
    color: T.dim,
    fontSize: 10,
    letterSpacing: 0.4,
  },

  heroFootRow: {
    marginTop: 16,
    paddingTop: 12,
    width: '100%',
    borderTopWidth: 1,
    borderTopColor: T.line2,
    borderStyle: 'dashed',
    alignItems: 'center',
  },
  heroFootText: { fontFamily: MONO, fontSize: 10, color: T.dim, letterSpacing: 0.4 },

  loadErrorText: {
    marginTop: 10,
    color: T.faint,
    fontSize: 11,
    textAlign: 'center',
  },

  // ── verdict pill ────────────────────────────────────────────────────────
  verdictPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
  },
  verdictDot: { width: 6, height: 6, borderRadius: 6, marginRight: 8 },
  verdictPillText: {
    fontFamily: MONO,
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  verdictPillSub: {
    fontFamily: MONO,
    fontSize: 10,
    letterSpacing: 0.8,
    fontWeight: '500',
    opacity: 0.8,
  },

  // ── dimensions ──────────────────────────────────────────────────────────
  dimRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dimName: {
    fontSize: 12.5,
    color: T.dim,
    width: 100,
    fontWeight: '500',
  },
  dimTrack: {
    flex: 1,
    height: 4,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.06)',
    overflow: 'hidden',
  },
  dimFill: {
    height: '100%',
    backgroundColor: T.purple,
    borderRadius: 4,
  },
  dimScore: {
    fontFamily: MONO,
    fontSize: 12,
    fontWeight: '600',
    color: T.ink,
    width: 30,
    textAlign: 'right',
  },

  // ── metrics ─────────────────────────────────────────────────────────────
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  metricOuter: {
    width: '48%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: T.line2,
    overflow: 'hidden',
  },
  metric: {
    padding: 14,
  },
  metricLabel: {
    fontFamily: MONO,
    fontSize: 9.5,
    color: T.faint,
    letterSpacing: 1.2,
    marginBottom: 6,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: '700',
    color: T.ink,
    letterSpacing: -0.4,
  },
  metricChange: {
    fontFamily: MONO,
    fontSize: 11,
    marginTop: 4,
    letterSpacing: 0.4,
  },

  // ── agent cards ─────────────────────────────────────────────────────────
  agentCardOuter: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: T.line2,
    overflow: 'hidden',
  },
  agentCard: {
    padding: 14,
  },
  agentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  agentIconBubble: {
    width: 36,
    height: 36,
    borderRadius: 11,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  agentName: { color: T.ink, fontSize: 13.5, fontWeight: '600', letterSpacing: -0.2 },
  agentRole: { fontFamily: MONO, fontSize: 9.5, color: T.faint, letterSpacing: 1.2, marginTop: 2 },
  agentBadge: {
    paddingVertical: 4,
    paddingHorizontal: 9,
    borderRadius: 6,
    borderWidth: 1,
  },
  agentBadgeText: {
    fontFamily: MONO,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.8,
  },
  agentBody: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: T.line2,
    borderStyle: 'dashed',
  },
  agentBodyText: {
    fontSize: 12.5,
    color: T.dim,
    lineHeight: 20,
  },
  findingsList: {
    marginTop: 10,
    gap: 8,
  },
  findingRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  findingDot: {
    width: 5,
    height: 5,
    borderRadius: 5,
    marginTop: 7,
  },
  findingText: {
    flex: 1,
    fontSize: 12.5,
    color: T.dim,
    lineHeight: 18,
  },

  // ── deliverables ────────────────────────────────────────────────────────
  cvoAutoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cvoAuto: {
    fontFamily: MONO,
    fontSize: 9,
    color: T.purple,
    letterSpacing: 1.2,
    fontWeight: '600',
  },
  delivOuter: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: T.line2,
    overflow: 'hidden',
  },
  deliv: {
    padding: 14,
  },
  delivHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  delivIconBubble: {
    width: 36,
    height: 36,
    borderRadius: 11,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  delivTitle: { color: T.ink, fontSize: 13.5, fontWeight: '600', letterSpacing: -0.2 },
  delivSub: { fontFamily: MONO, fontSize: 10, color: T.faint, marginTop: 2, letterSpacing: 0.4 },
  delivBody: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: T.line2,
    borderStyle: 'dashed',
    gap: 10,
  },
  delivBulletRow: {
    flexDirection: 'row',
    gap: 10,
  },
  delivNum: {
    fontFamily: MONO,
    fontSize: 10.5,
    color: T.purple,
    fontWeight: '600',
    letterSpacing: 0.6,
    marginTop: 1,
  },
  delivBulletText: {
    flex: 1,
    fontSize: 13,
    color: T.dim,
    lineHeight: 19,
  },

  // ── CTA ─────────────────────────────────────────────────────────────────
  ctaTouchable: {
    width: '100%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    overflow: 'hidden',
  },
  cta: {
    paddingVertical: 15,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
  },
  ctaText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: -0.3,
  },
});
