import React, { useEffect, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Animated,
  Linking,
  Platform,
  SafeAreaView,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import Svg, { Circle, Defs, LinearGradient as SvgLinearGradient, Stop } from 'react-native-svg';
import * as WebBrowser from 'expo-web-browser';
import {
  CircleDollarSign,
  Crown,
  FileEdit,
  FileQuestion,
  FileText,
  LucideIcon,
  Search,
  Sparkles,
} from 'lucide-react-native';

import { API_BASE_URL, getAnalysis, getAuthToken } from '../services/api';
import type { AgentReport, ReportData, Verdict } from '../services/types';
import { findingColor } from '../services/types';
import { useReports } from '../context/ReportsContext';

// ─── design tokens (mirrors app/index.tsx + how-they-work.tsx) ─────────────
const T = {
  bg: '#08080d',
  ink: '#ffffff',
  dim: 'rgba(255,255,255,0.56)',
  faint: 'rgba(255,255,255,0.36)',
  ghost: 'rgba(255,255,255,0.22)',
  line: 'rgba(255,255,255,0.07)',
  line2: 'rgba(255,255,255,0.12)',
  glass: 'rgba(255,255,255,0.035)',
  purple: '#9550ee',
  purpleSoft: 'rgba(149,80,238,0.18)',
  purpleEdge: 'rgba(149,80,238,0.45)',
  purpleInk: '#d6c0ff',
  green: '#3ddc97',
  amber: '#f0b34a',
  red: '#ff5d6c',
};
const MONO = Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }) as string;

// ─── placeholder report (used when navigated without an id) ────────────────
const PLACEHOLDER_REPORT: ReportData = {
  startup_name: 'Bykea',
  intent: 'invest',
  tags: ['Mobility', 'Series A', 'Karachi', 'B2C'],
  score: 551,
  verdict: 'INVEST',
  verdict_sub: 'WITH CONDITIONS',
  dimensions: [
    { name: 'Market fit', score: 72 },
    { name: 'Financials', score: 62 },
    { name: 'Brand power', score: 74 },
    { name: 'Strategy', score: 68 },
  ],
  metrics: [
    { label: 'Est. valuation', value: '$28M', change: '+12% YoY', change_type: 'positive' },
    { label: 'Monthly GMV', value: '₨ 2.4B', change: 'Growing', change_type: 'positive' },
    { label: 'Burn rate / mo', value: '$180K', change: 'High risk', change_type: 'negative' },
    { label: 'Runway est.', value: '14 mo', change: 'Watch', change_type: 'warning' },
  ],
  agent_reports: [],
};

// ─── verdict pill mapping ──────────────────────────────────────────────────
const VERDICT_TONE: Record<Verdict, { bg: string; border: string; ink: string }> = {
  INVEST:  { bg: 'rgba(61,220,151,0.12)',  border: 'rgba(61,220,151,0.45)',  ink: T.green },
  WATCH:   { bg: 'rgba(240,179,74,0.12)',  border: 'rgba(240,179,74,0.45)',  ink: T.amber },
  REJECT:  { bg: 'rgba(255,93,108,0.10)',  border: 'rgba(255,93,108,0.40)',  ink: T.red },
  ACQUIRE: { bg: 'rgba(149,80,238,0.14)',  border: 'rgba(149,80,238,0.55)',  ink: T.purpleInk },
};

// ─── agent icon mapping (matches app/loading.tsx + how-they-work.tsx) ──────
const AGENT_META: Record<number, { Icon: LucideIcon; color: string }> = {
  1: { Icon: Search,           color: '#FF6B6B' },
  2: { Icon: CircleDollarSign, color: '#D4FF3D' },
  3: { Icon: Sparkles,         color: '#A78BFA' },
  4: { Icon: Crown,            color: '#FFC83C' },
};

// ─── deliverables (auto-generated by the CVO) ──────────────────────────────
const DELIVERABLES: { key: string; icon: LucideIcon; title: string; sub: string; color: string }[] = [
  { key: 'brief',     icon: FileText,     title: 'Investor Brief',    sub: '2-page PDF · tl;dr + appendix',  color: T.purple },
  { key: 'questions', icon: FileQuestion, title: 'Questions to Ask',  sub: '12 sharp questions for the founder', color: T.purpleInk },
  { key: 'memo',      icon: FileEdit,     title: 'Deal Memo Draft',   sub: 'Editable doc · 800 words',          color: T.amber },
];

function buildBullets(report: ReportData, key: string): string[] {
  if (key === 'brief') {
    return [
      `Aura Score: ${report.score} / 1000`,
      `Verdict: ${report.verdict}${report.verdict_sub ? ` · ${report.verdict_sub}` : ''}`,
      report.tags[0] ? `Sector: ${report.tags[0]}` : 'Sector: —',
      `Dimensions: ${report.dimensions.map((d) => `${d.name} ${d.score}`).join(' · ')}`,
    ];
  }
  if (key === 'questions') {
    const negatives = report.agent_reports
      .flatMap((r) => r.findings)
      .filter((f) => f.type === 'negative' || f.type === 'warning')
      .slice(0, 4)
      .map((f) => f.text);
    return negatives.length ? negatives : ['Margin path?', 'Unit econ at scale?', 'Cash runway?'];
  }
  return [
    `Thesis · ${report.verdict.toLowerCase()} · ${report.startup_name}`,
    `Market · ${report.tags[0] || 'unknown'}`,
    `Risks · ${report.agent_reports
      .flatMap((r) => r.findings)
      .filter((f) => f.type !== 'positive')
      .slice(0, 2)
      .map((f) => f.text.slice(0, 40))
      .join('; ') || 'see findings'}`,
    `Recommendation · ${report.verdict}${report.verdict_sub ? ` · ${report.verdict_sub}` : ''}`,
  ];
}

// ─── small reusable: section header ────────────────────────────────────────
function SectionHead({ eyebrow, title, meta }: { eyebrow: string; title: string; meta?: React.ReactNode }) {
  return (
    <View style={s.sectionHead}>
      <View>
        <Text style={s.eyebrow}>{eyebrow}</Text>
        <Text style={s.sectionTitle}>{title}</Text>
      </View>
      {meta}
    </View>
  );
}

// ─── verdict pill ──────────────────────────────────────────────────────────
function VerdictPill({ verdict, sub }: { verdict: Verdict; sub?: string }) {
  const m = VERDICT_TONE[verdict] ?? VERDICT_TONE.WATCH;
  const label = verdict;
  return (
    <View style={[s.verdictPill, { backgroundColor: m.bg, borderColor: m.border }]}>
      <View style={[s.verdictDot, { backgroundColor: m.ink }]} />
      <Text style={[s.verdictPillText, { color: m.ink }]}>{label}</Text>
      {sub && <Text style={[s.verdictPillSub, { color: m.ink }]}> · {sub}</Text>}
    </View>
  );
}

// ─── aura ring (svg) ───────────────────────────────────────────────────────
function AuraRing({ score, max = 1000, size = 168 }: { score: number; max?: number; size?: number }) {
  const r = (size - 20) / 2;
  const C0 = 2 * Math.PI * r;
  const pct = Math.max(0, Math.min(1, score / max));
  const offset = C0 * (1 - pct);
  return (
    <Svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
      <Defs>
        <SvgLinearGradient id="auraRingReport" x1="0" y1="0" x2="1" y2="1">
          <Stop offset="0%" stopColor="#c79bff" />
          <Stop offset="50%" stopColor="#9550ee" />
          <Stop offset="100%" stopColor="#5b2ea3" />
        </SvgLinearGradient>
      </Defs>
      <Circle cx={size / 2} cy={size / 2} r={r} stroke="rgba(255,255,255,0.06)" strokeWidth={6} fill="none" />
      {score > 0 && (
        <>
          {/* Halo layers for the purple glow (RN-SVG has no drop-shadow). */}
          <Circle
            cx={size / 2}
            cy={size / 2}
            r={r}
            stroke="#9550ee"
            strokeWidth={20}
            opacity={0.12}
            fill="none"
            strokeLinecap="round"
            strokeDasharray={C0}
            strokeDashoffset={offset}
            transform={`rotate(-90 ${size / 2} ${size / 2})`}
          />
          <Circle
            cx={size / 2}
            cy={size / 2}
            r={r}
            stroke="#9550ee"
            strokeWidth={12}
            opacity={0.28}
            fill="none"
            strokeLinecap="round"
            strokeDasharray={C0}
            strokeDashoffset={offset}
            transform={`rotate(-90 ${size / 2} ${size / 2})`}
          />
          <Circle
            cx={size / 2}
            cy={size / 2}
            r={r}
            stroke="url(#auraRingReport)"
            strokeWidth={6}
            fill="none"
            strokeLinecap="round"
            strokeDasharray={C0}
            strokeDashoffset={offset}
            transform={`rotate(-90 ${size / 2} ${size / 2})`}
          />
        </>
      )}
    </Svg>
  );
}

// ─── dimension bar ─────────────────────────────────────────────────────────
function DimBar({ name, score }: { name: string; score: number }) {
  return (
    <View style={s.dimRow}>
      <Text style={s.dimName} numberOfLines={1}>{name}</Text>
      <View style={s.dimTrack}>
        <View style={[s.dimFill, { width: `${Math.max(0, Math.min(100, score))}%` }]} />
      </View>
      <Text style={s.dimScore}>{score}</Text>
    </View>
  );
}

// ─── metric card (2-up grid) ───────────────────────────────────────────────
function MetricCard({ label, value, change, changeColor }: { label: string; value: string; change: string; changeColor: string }) {
  return (
    <View style={s.metricOuter}>
      <LinearGradient
        colors={['rgba(255,255,255,0.045)', 'rgba(255,255,255,0.012)']}
        start={{ x: 0, y: 0 }}
        end={{ x: 0, y: 1 }}
        style={s.metric}
      >
        <Text style={s.metricLabel}>{label.toUpperCase()}</Text>
        <Text style={s.metricValue}>{value}</Text>
        <Text style={[s.metricChange, { color: changeColor }]}>{change}</Text>
      </LinearGradient>
    </View>
  );
}

// ─── agent report card (expandable) ────────────────────────────────────────
function AgentCard({
  agentId,
  name,
  role,
  badge,
  body,
  findings,
  expanded,
  onToggle,
}: {
  agentId: number;
  name: string;
  role: string;
  badge: string;
  body: string;
  findings: { text: string; color: string }[];
  expanded: boolean;
  onToggle: () => void;
}) {
  const meta = AGENT_META[agentId] ?? AGENT_META[1];
  return (
    <View style={s.agentCardOuter}>
      <TouchableOpacity onPress={onToggle} activeOpacity={0.85}>
        <LinearGradient
          colors={
            expanded
              ? ['rgba(149,80,238,0.10)', 'rgba(149,80,238,0.02)']
              : ['rgba(255,255,255,0.045)', 'rgba(255,255,255,0.012)']
          }
          start={{ x: 0, y: 0 }}
          end={{ x: 0, y: 1 }}
          style={s.agentCard}
        >
          <View style={s.agentHeader}>
            <View
              style={[
                s.agentIconBubble,
                { backgroundColor: `${meta.color}1f`, borderColor: `${meta.color}55` },
              ]}
            >
              <meta.Icon size={18} color={meta.color} />
            </View>
            <View style={{ flex: 1, minWidth: 0 }}>
              <Text style={s.agentName}>{name}</Text>
              <Text style={s.agentRole}>{role.toUpperCase()}</Text>
            </View>
            <View
              style={[
                s.agentBadge,
                { backgroundColor: `${meta.color}1f`, borderColor: `${meta.color}55` },
              ]}
            >
              <Text style={[s.agentBadgeText, { color: meta.color }]}>{badge}</Text>
            </View>
            <Ionicons
              name={expanded ? 'chevron-up' : 'chevron-down'}
              size={14}
              color={T.faint}
              style={{ marginLeft: 8 }}
            />
          </View>

          {expanded && (
            <View style={s.agentBody}>
              <Text style={s.agentBodyText}>{body}</Text>
              {findings.length > 0 && (
                <View style={s.findingsList}>
                  {findings.map((f, i) => (
                    <View key={i} style={s.findingRow}>
                      <View style={[s.findingDot, { backgroundColor: f.color }]} />
                      <Text style={s.findingText}>{f.text}</Text>
                    </View>
                  ))}
                </View>
              )}
            </View>
          )}
        </LinearGradient>
      </TouchableOpacity>
    </View>
  );
}

// ─── deliverable card (expandable) ─────────────────────────────────────────
function DeliverableItem({
  item,
  bullets,
  expanded,
  onToggle,
}: {
  item: (typeof DELIVERABLES)[number];
  bullets: string[];
  expanded: boolean;
  onToggle: () => void;
}) {
  const Icon = item.icon;
  return (
    <View style={s.delivOuter}>
      <TouchableOpacity onPress={onToggle} activeOpacity={0.85}>
        <LinearGradient
          colors={['rgba(255,255,255,0.045)', 'rgba(255,255,255,0.012)']}
          start={{ x: 0, y: 0 }}
          end={{ x: 0, y: 1 }}
          style={[s.deliv, { borderLeftWidth: 3, borderLeftColor: item.color }]}
        >
          <View style={s.delivHead}>
            <View
              style={[
                s.delivIconBubble,
                { backgroundColor: `${item.color}1f`, borderColor: `${item.color}55` },
              ]}
            >
              <Icon size={18} color={item.color} />
            </View>
            <View style={{ flex: 1, minWidth: 0 }}>
              <Text style={s.delivTitle}>{item.title}</Text>
              <Text style={s.delivSub}>{item.sub}</Text>
            </View>
            <Ionicons
              name={expanded ? 'remove' : 'add'}
              size={18}
              color={T.faint}
              style={{ marginLeft: 8 }}
            />
          </View>

          {expanded && (
            <View style={s.delivBody}>
              {bullets.map((b, i) => (
                <View key={i} style={s.delivBulletRow}>
                  <Text style={s.delivNum}>{(i + 1).toString().padStart(2, '0')}</Text>
                  <Text style={s.delivBulletText}>{b}</Text>
                </View>
              ))}
            </View>
          )}
        </LinearGradient>
      </TouchableOpacity>
    </View>
  );
}

// ─── main screen ───────────────────────────────────────────────────────────
export default function ReportScreen() {
  const router = useRouter();
  const { name, id } = useLocalSearchParams<{ name: string; id?: string }>();

  const { reports, addReport, refresh: refreshReports } = useReports();

  // Re-pull the dashboard's recent-analyses list before navigating home, so
  // the new run (or any other side-effect that landed mid-session) shows up
  // immediately rather than after the next auth flip.
  const handleReturnHome = () => {
    void refreshReports();
    router.back();
  };
  const handleNewAnalysis = () => {
    void refreshReports();
    router.push('/');
  };

  // When viewing from history (no backend id), hydrate the placeholder with
  // whatever we already know about this run (name + summary). This avoids
  // showing Bykea data when the user taps Retailo from the recent list.
  const [report, setReport] = useState<ReportData | null>(() => {
    if (id) return null;
    const matched = name
      ? reports.find((r) => r.name.toLowerCase() === name.toLowerCase())
      : undefined;
    if (name || matched) {
      // Saved verdicts can be PIVOT/ITERATE which aren't in ReportData's
      // narrower Verdict union — VerdictPill falls back to WATCH styling
      // for those, so it's safe to cast.
      const verdict = (matched?.verdict ?? PLACEHOLDER_REPORT.verdict) as ReportData['verdict'];
      return {
        ...PLACEHOLDER_REPORT,
        startup_name: matched?.name ?? name ?? PLACEHOLDER_REPORT.startup_name,
        score: matched?.score ?? PLACEHOLDER_REPORT.score,
        verdict,
        verdict_sub: undefined,
      };
    }
    return PLACEHOLDER_REPORT;
  });
  const [loadError, setLoadError] = useState<string | null>(null);

  // The store-write is now done ONLY inside the getAnalysis success branch
  // below, so the placeholder fallback can never leak Bykea into history.
  // Kept a ref to ensure we never double-add if the screen re-renders.
  const savedRef = useRef(false);

  // Build a placeholder display object that uses the user's actual startup
  // name (from the URL) so a backend failure doesn't show "Bykea" instead
  // of e.g. "Retailo".
  const placeholderWithUrlName = (): ReportData => ({
    ...PLACEHOLDER_REPORT,
    startup_name: name ?? PLACEHOLDER_REPORT.startup_name,
  });

  // Load real analysis when an id is passed.
  useEffect(() => {
    if (!id) return;
    let cancelled = false;
    getAnalysis(id)
      .then((a) => {
        if (cancelled) return;
        if (a.report) {
          setReport(a.report);
          // Save the REAL report to the dashboard store — and only here.
          // Never on placeholder fallback, never on history navigation.
          if (!savedRef.current) {
            savedRef.current = true;
            const dims = a.report.dimensions
              .slice(0, 3)
              .map((d) => ({ label: d.name, val: d.score }));
            addReport({
              id,
              name: a.report.startup_name,
              score: a.report.score,
              verdict: a.report.verdict,
              breakdowns: dims,
            });
          }
        } else if (a.status === 'failed') {
          setLoadError(a.error || 'Analysis failed.');
          setReport(placeholderWithUrlName());
        } else {
          setReport(placeholderWithUrlName());
        }
      })
      .catch((e) => {
        if (cancelled) return;
        setLoadError(e?.message || 'Could not load report.');
        setReport(placeholderWithUrlName());
      });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  // Animated score countup (0 → target over 1500ms with eased curve).
  const target = report?.score ?? 0;
  const startupName = report?.startup_name || name || 'Bykea';
  const [score, setScore] = useState(0);

  useEffect(() => {
    if (!report) return;
    const duration = 1500;
    const startTime = Date.now();
    let rafId: number;
    const animateScore = () => {
      const now = Date.now();
      const progress = Math.min((now - startTime) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      setScore(Math.round(eased * target));
      if (progress < 1) {
        rafId = requestAnimationFrame(animateScore);
      }
    };
    rafId = requestAnimationFrame(animateScore);
    return () => cancelAnimationFrame(rafId);
  }, [report, target]);

  // Expand/collapse state — first item open by default.
  const [expandedAgent, setExpandedAgent] = useState<number | null>(1);
  const [expandedDeliv, setExpandedDeliv] = useState<string | null>('brief');

  // Open the backend-generated PDF for this run. Backend renders the
  // canonical, fully-formatted document; the local HTML-to-PDF approach
  // only re-exported the on-screen UI and lost most of the real content.
  const handleDownloadPdf = async () => {
    if (!id) {
      Alert.alert('Error', 'Cannot download report: No analysis ID available.');
      return;
    }
    const token = getAuthToken();
    if (!token) {
      Alert.alert('Download Failed', 'You need to be signed in to download the report.');
      return;
    }
    const pdfUrl = `${API_BASE_URL}/api/analyses/${id}/pdf`;
    const safeName = (startupName || 'report').replace(/\s+/g, '_');
    const filename = `${safeName}_due_diligence.pdf`;
    const authHeader = { Authorization: `Bearer ${token}` };

    // Pre-flight: surface a friendly error instead of showing the JSON 401/404 in a new tab.
    try {
      const probe = await fetch(pdfUrl, {
        method: 'GET',
        headers: { ...authHeader, Range: 'bytes=0-0' },
      });
      if (!probe.ok) {
        let msg = `HTTP ${probe.status}`;
        try {
          const body = await probe.json();
          if (body?.detail) msg = String(body.detail);
        } catch {
          // not JSON — keep status code
        }
        Alert.alert('Download Failed', msg);
        return;
      }
    } catch {
      Alert.alert('Download Failed', 'Could not reach the server. Is the backend running?');
      return;
    }

    if (Platform.OS === 'web') {
      try {
        const res = await fetch(pdfUrl, { headers: authHeader });
        const blob = await res.blob();
        const blobUrl = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = blobUrl;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        a.remove();
        URL.revokeObjectURL(blobUrl);
        return;
      } catch {
        // fall through to browser open
      }
    }

    // Native: external browser can't carry the Authorization header, so we
    // pass the token as a query param — the backend accepts it as a fallback.
    const pdfUrlWithToken = `${pdfUrl}?token=${encodeURIComponent(token)}`;
    try {
      await WebBrowser.openBrowserAsync(pdfUrlWithToken);
    } catch {
      Linking.openURL(pdfUrlWithToken).catch(() => {
        Alert.alert('Download Failed', 'Could not open the PDF report link.');
      });
    }
  };

  const handleShare = async () => {
    if (!id) return;
    const token = getAuthToken();
    // Token-bearing URL so the recipient (or the same user in another tab)
    // can actually open the PDF. For a hackathon scope this is fine; in
    // production we'd mint a short-lived signed share token instead.
    const pdfUrl = token
      ? `${API_BASE_URL}/api/analyses/${id}/pdf?token=${encodeURIComponent(token)}`
      : `${API_BASE_URL}/api/analyses/${id}/pdf`;
    const score = report?.score ?? '—';
    const verdict = report?.verdict ?? '';
    const message = `VibeInvest due diligence for ${startupName} · Aura ${score} · ${verdict}\n${pdfUrl}`;

    if (Platform.OS === 'web') {
      try {
        if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
          await navigator.clipboard.writeText(message);
          Alert.alert('Link Copied', 'Report link & summary copied to clipboard.');
          return;
        }
      } catch {
        // fall through to Share.share
      }
    }
    try {
      await Share.share({
        message,
        url: pdfUrl,
        title: `${startupName} Due Diligence Report`,
      });
    } catch {
      Alert.alert('Share Failed', 'Could not share the due diligence report.');
    }
  };

  if (!report) {
    return (
      <SafeAreaView style={[s.screen, { alignItems: 'center', justifyContent: 'center' }]}>
        <ActivityIndicator color={T.purple} />
        <Text style={s.loadingText}>loading report…</Text>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={s.screen}>
      {/* ── header ── */}
      <View style={s.header}>
        <TouchableOpacity
          onPress={handleReturnHome}
          style={s.headerBtn}
          accessibilityLabel="Back"
          hitSlop={10}
        >
          <Ionicons name="chevron-back" size={22} color={T.ink} />
        </TouchableOpacity>
        <Text style={s.headerTitle}>Report</Text>
        <View style={s.headerActions}>
          <TouchableOpacity
            onPress={handleDownloadPdf}
            style={s.headerBtn}
            accessibilityLabel="Save report as PDF"
            hitSlop={10}
          >
            <Ionicons name="save-outline" size={20} color={T.ink} />
          </TouchableOpacity>
        </View>
      </View>

      <ScrollView contentContainerStyle={{ paddingBottom: 36 }} showsVerticalScrollIndicator={false}>
        {/* ── hero (aura score + verdict) ── */}
        <View style={{ paddingHorizontal: 20, marginTop: 14 }}>
          <View style={s.heroOuter}>
            <LinearGradient
              colors={['rgba(40,24,72,0.65)', 'rgba(14,11,24,0.85)']}
              locations={[0, 0.6]}
              start={{ x: 0.3, y: 0 }}
              end={{ x: 0.7, y: 1 }}
              style={s.hero}
            >
              <Text style={s.eyebrow}>◢ AURA SCORE · FINAL</Text>
              <Text style={s.startupName}>{startupName}</Text>

              <View style={s.heroRingWrap}>
                <AuraRing score={score} size={184} />
                <View style={s.heroRingCenter} pointerEvents="none">
                  <Text style={s.bigScore}>{score}</Text>
                  <Text style={s.scoreMax}>/ 1000</Text>
                </View>
              </View>

              <VerdictPill verdict={report.verdict} sub={report.verdict_sub ?? undefined} />

              {/* tags */}
              {report.tags.length > 0 && (
                <View style={s.tagsRow}>
                  {report.tags.slice(0, 5).map((t, i) => (
                    <View key={`${t}-${i}`} style={s.tag}>
                      <Text style={s.tagText}>{t}</Text>
                    </View>
                  ))}
                </View>
              )}

              <View style={s.heroFootRow}>
                <Text style={s.heroFootText}>⌁ Confidence 0.91 · 4/4 agents</Text>
              </View>
            </LinearGradient>
          </View>

          {loadError && (
            <Text style={s.loadErrorText}>showing placeholder · {loadError}</Text>
          )}
        </View>

        {/* ── dimensions ── */}
        <View style={s.section}>
          <SectionHead eyebrow="◢ DIMENSIONS" title="Score breakdown" />
          <View style={{ gap: 12 }}>
            {report.dimensions.map((d) => (
              <DimBar key={d.name} name={d.name} score={d.score} />
            ))}
          </View>
        </View>

        {/* ── key metrics ── */}
        <View style={s.section}>
          <SectionHead eyebrow="◢ KEY METRICS" title="By the numbers" />
          {report.metrics.length === 0 ? (
            <Text style={s.emptyText}>No metrics surfaced.</Text>
          ) : (
            <View style={s.metricsGrid}>
              {report.metrics.map((m, i) => (
                <MetricCard
                  key={`${m.label}-${i}`}
                  label={m.label}
                  value={m.value}
                  change={m.change}
                  changeColor={findingColor(m.change_type)}
                />
              ))}
            </View>
          )}
        </View>

        {/* ── agent reports ── */}
        <View style={s.section}>
          <SectionHead eyebrow="◢ AGENT REPORTS" title="What each agent found" />
          {report.agent_reports.length === 0 ? (
            <Text style={s.emptyText}>No agent reports yet.</Text>
          ) : (
            <View style={{ gap: 10 }}>
              {report.agent_reports.map((r: AgentReport) => (
                <AgentCard
                  key={r.id}
                  agentId={r.id}
                  name={r.name}
                  role={r.role}
                  badge={r.badge || '—'}
                  body={r.body}
                  findings={r.findings.map((f) => ({ text: f.text, color: findingColor(f.type) }))}
                  expanded={expandedAgent === r.id}
                  onToggle={() => setExpandedAgent(expandedAgent === r.id ? null : r.id)}
                />
              ))}
            </View>
          )}
        </View>

        {/* ── deliverables ── */}
        <View style={s.section}>
          <SectionHead
            eyebrow="◢ DELIVERABLES"
            title="Generate"
            meta={
              <View style={s.cvoAutoRow}>
                <Sparkles size={11} color={T.purple} style={{ marginRight: 4 }} />
                <Text style={s.cvoAuto}>CVO AUTO-GENERATED</Text>
              </View>
            }
          />
          <View style={{ gap: 10 }}>
            {DELIVERABLES.map((item) => (
              <DeliverableItem
                key={item.key}
                item={item}
                bullets={buildBullets(report, item.key)}
                expanded={expandedDeliv === item.key}
                onToggle={() => setExpandedDeliv(expandedDeliv === item.key ? null : item.key)}
              />
            ))}
          </View>
        </View>

        {/* ── CTA ── */}
        <View style={{ paddingHorizontal: 20, marginTop: 28 }}>
          <TouchableOpacity
            onPress={handleNewAnalysis}
            accessibilityLabel="Start a new analysis"
            activeOpacity={0.85}
            style={s.ctaTouchable}
          >
            <LinearGradient
              colors={['#9550ee', '#7b3bd9']}
              start={{ x: 0, y: 0 }}
              end={{ x: 0, y: 1 }}
              style={s.cta}
            >
              <Text style={s.ctaText}>New Analysis</Text>
              <Ionicons name="arrow-forward" size={16} color="#fff" style={{ marginLeft: 8 }} />
            </LinearGradient>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

// ─── styles ────────────────────────────────────────────────────────────────
const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: T.bg },
  loadingText: { color: T.faint, marginTop: 12, fontSize: 12, letterSpacing: 0.6 },

  // header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: T.line,
  },
  headerBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: T.ink,
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: -0.2,
  },
  headerActions: { flexDirection: 'row', alignItems: 'center' },

  // section header
  sectionHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 12,
  },
  eyebrow: {
    fontFamily: MONO,
    fontSize: 9.5,
    color: T.faint,
    letterSpacing: 1.4,
    marginBottom: 3,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: T.ink,
    letterSpacing: -0.3,
  },

  // section wrapper
  section: { paddingHorizontal: 20, marginTop: 26 },
  emptyText: { color: T.ghost, fontSize: 12 },

  // ── hero ────────────────────────────────────────────────────────────────
  heroOuter: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.purpleEdge,
    overflow: 'hidden',
    shadowColor: T.purple,
    shadowOpacity: 0.2,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  hero: {
    padding: 22,
    alignItems: 'center',
  },
  startupName: {
    fontSize: 22,
    fontWeight: '600',
    color: T.ink,
    letterSpacing: -0.4,
    marginTop: 4,
    marginBottom: 10,
    textAlign: 'center',
  },
  heroRingWrap: {
    width: 184,
    height: 184,
    position: 'relative',
    marginBottom: 16,
  },
  heroRingCenter: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bigScore: {
    fontSize: 58,
    fontWeight: '500',
    color: T.ink,
    letterSpacing: -2,
    lineHeight: 60,
  },
  scoreMax: {
    fontFamily: MONO,
    fontSize: 11,
    color: T.faint,
    letterSpacing: 0.8,
    marginTop: 4,
  },

  // tags
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'center',
    marginTop: 14,
  },
  tag: {
    paddingVertical: 3,
    paddingHorizontal: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.line2,
  },
  tagText: {
    color: T.dim,
    fontSize: 10,
    letterSpacing: 0.4,
  },

  heroFootRow: {
    marginTop: 16,
    paddingTop: 12,
    width: '100%',
    borderTopWidth: 1,
    borderTopColor: T.line2,
    borderStyle: 'dashed',
    alignItems: 'center',
  },
  heroFootText: { fontFamily: MONO, fontSize: 10, color: T.dim, letterSpacing: 0.4 },

  loadErrorText: {
    marginTop: 10,
    color: T.faint,
    fontSize: 11,
    textAlign: 'center',
  },

  // ── verdict pill ────────────────────────────────────────────────────────
  verdictPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
  },
  verdictDot: { width: 6, height: 6, borderRadius: 6, marginRight: 8 },
  verdictPillText: {
    fontFamily: MONO,
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  verdictPillSub: {
    fontFamily: MONO,
    fontSize: 10,
    letterSpacing: 0.8,
    fontWeight: '500',
    opacity: 0.8,
  },

  // ── dimensions ──────────────────────────────────────────────────────────
  dimRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dimName: {
    fontSize: 12.5,
    color: T.dim,
    width: 100,
    fontWeight: '500',
  },
  dimTrack: {
    flex: 1,
    height: 4,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.06)',
    overflow: 'hidden',
  },
  dimFill: {
    height: '100%',
    backgroundColor: T.purple,
    borderRadius: 4,
  },
  dimScore: {
    fontFamily: MONO,
    fontSize: 12,
    fontWeight: '600',
    color: T.ink,
    width: 30,
    textAlign: 'right',
  },

  // ── metrics ─────────────────────────────────────────────────────────────
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  metricOuter: {
    width: '48%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: T.line2,
    overflow: 'hidden',
  },
  metric: {
    padding: 14,
  },
  metricLabel: {
    fontFamily: MONO,
    fontSize: 9.5,
    color: T.faint,
    letterSpacing: 1.2,
    marginBottom: 6,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: '700',
    color: T.ink,
    letterSpacing: -0.4,
  },
  metricChange: {
    fontFamily: MONO,
    fontSize: 11,
    marginTop: 4,
    letterSpacing: 0.4,
  },

  // ── agent cards ─────────────────────────────────────────────────────────
  agentCardOuter: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: T.line2,
    overflow: 'hidden',
  },
  agentCard: {
    padding: 14,
  },
  agentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  agentIconBubble: {
    width: 36,
    height: 36,
    borderRadius: 11,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  agentName: { color: T.ink, fontSize: 13.5, fontWeight: '600', letterSpacing: -0.2 },
  agentRole: { fontFamily: MONO, fontSize: 9.5, color: T.faint, letterSpacing: 1.2, marginTop: 2 },
  agentBadge: {
    paddingVertical: 4,
    paddingHorizontal: 9,
    borderRadius: 6,
    borderWidth: 1,
  },
  agentBadgeText: {
    fontFamily: MONO,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.8,
  },
  agentBody: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: T.line2,
    borderStyle: 'dashed',
  },
  agentBodyText: {
    fontSize: 12.5,
    color: T.dim,
    lineHeight: 20,
  },
  findingsList: {
    marginTop: 10,
    gap: 8,
  },
  findingRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  findingDot: {
    width: 5,
    height: 5,
    borderRadius: 5,
    marginTop: 7,
  },
  findingText: {
    flex: 1,
    fontSize: 12.5,
    color: T.dim,
    lineHeight: 18,
  },

  // ── deliverables ────────────────────────────────────────────────────────
  cvoAutoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cvoAuto: {
    fontFamily: MONO,
    fontSize: 9,
    color: T.purple,
    letterSpacing: 1.2,
    fontWeight: '600',
  },
  delivOuter: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: T.line2,
    overflow: 'hidden',
  },
  deliv: {
    padding: 14,
  },
  delivHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  delivIconBubble: {
    width: 36,
    height: 36,
    borderRadius: 11,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  delivTitle: { color: T.ink, fontSize: 13.5, fontWeight: '600', letterSpacing: -0.2 },
  delivSub: { fontFamily: MONO, fontSize: 10, color: T.faint, marginTop: 2, letterSpacing: 0.4 },
  delivBody: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: T.line2,
    borderStyle: 'dashed',
    gap: 10,
  },
  delivBulletRow: {
    flexDirection: 'row',
    gap: 10,
  },
  delivNum: {
    fontFamily: MONO,
    fontSize: 10.5,
    color: T.purple,
    fontWeight: '600',
    letterSpacing: 0.6,
    marginTop: 1,
  },
  delivBulletText: {
    flex: 1,
    fontSize: 13,
    color: T.dim,
    lineHeight: 19,
  },

  // ── CTA ─────────────────────────────────────────────────────────────────
  ctaTouchable: {
    width: '100%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    overflow: 'hidden',
  },
  cta: {
    paddingVertical: 15,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
  },
  ctaText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: -0.3,
  },
});
