import json
import logging
from typing import Any, Literal

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field
from sse_starlette.sse import EventSourceResponse

log = logging.getLogger(__name__)

# VibeInvest uses google-adk as the primary boardroom runtime. The claude- and
# openai- comparison runners are optional bonus demos — if their agent dirs
# don't exist yet, skip registering those routes so the API still boots.
try:
    from api.services.claude_runner import run_pipeline as run_claude_pipeline
except Exception as exc:
    run_claude_pipeline = None
    log.warning("Claude runner unavailable: %s", exc)

try:
    from api.services.openai_runner import run_pipeline as run_openai_pipeline
except Exception as exc:
    run_openai_pipeline = None
    log.warning("OpenAI runner unavailable: %s", exc)

from api.services.google_adk_runner import run_pipeline as run_google_adk_pipeline

router = APIRouter(prefix="/api/run")


class BoardroomRequest(BaseModel):
    """VibeInvest pipeline input — what the founder submitted."""
    idea_text: str = Field(min_length=20, max_length=2000)
    output_language: Literal["en", "ur", "roman-ur"] = "en"


class LegacyRunRequest(BaseModel):
    """Backwards-compat shape used by the Claude / OpenAI comparison runners."""
    company_name: str


@router.post("/claude")
async def run_claude(request: LegacyRunRequest):
    if run_claude_pipeline is None:
        raise HTTPException(status_code=503, detail="Claude runner not available")

    async def event_generator():
        async for event in run_claude_pipeline(request.company_name):
            yield {"event": event["type"], "data": json.dumps(event)}

    return EventSourceResponse(event_generator())


@router.post("/openai")
async def run_openai(request: LegacyRunRequest):
    if run_openai_pipeline is None:
        raise HTTPException(status_code=503, detail="OpenAI runner not available")

    async def event_generator():
        async for event in run_openai_pipeline(request.company_name):
            yield {"event": event["type"], "data": json.dumps(event)}

    return EventSourceResponse(event_generator())


@router.post("/google-adk")
async def run_google_adk(request: BoardroomRequest):
    async def event_generator():
        async for event in run_google_adk_pipeline(
            idea_text=request.idea_text,
            output_language=request.output_language,
        ):
            yield {"event": event["type"], "data": json.dumps(event)}

    return EventSourceResponse(event_generator())


# ── Export route ───────────────────────────────────────────────────────────


def _render_markdown(final_report: dict) -> str:
    """Render a FinalReport dict as a Markdown share-able report.

    Defensive against missing keys — if the CVO produced a partial report,
    sections silently skip rather than crashing the export.
    """
    verdict = final_report.get("verdict", "unknown")
    aura = final_report.get("aura_score", 0)
    verdict_line = final_report.get("verdict_line", "")
    dimensions = final_report.get("dimensions", {})
    top_fixes = final_report.get("top_fixes", [])
    next_steps = final_report.get("next_steps", "")

    lines: list[str] = []
    lines.append(f"# VibeInvest — Verdict: {verdict.upper()}")
    lines.append("")
    lines.append(f"**Aura Score:** {aura} / 1000")
    if verdict_line:
        lines.append("")
        lines.append(f"> {verdict_line}")
    lines.append("")

    if dimensions:
        lines.append("## Dimensions")
        for name in ("market", "money", "brand", "strategy"):
            dim = dimensions.get(name)
            if not dim:
                continue
            lines.append(f"- **{name.capitalize()}** — {dim.get('score', '?')}/10. {dim.get('note', '')}")
        lines.append("")

    if top_fixes:
        lines.append("## Top fixes")
        for i, fix in enumerate(top_fixes, 1):
            lines.append(f"{i}. {fix}")
        lines.append("")

    if next_steps:
        lines.append("## Next steps")
        lines.append(next_steps)
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by VibeInvest — your AI boardroom for Pakistan's founders.*")
    return "\n".join(lines)


@router.get("/{run_id}/export")
async def export_run(run_id: str, request: Request, format: Literal["json", "md"] = "json"):
    """Download a completed run's FinalReport as JSON or Markdown.

    Reports are kept in memory (ring buffer, capacity 50) only — no DB.
    A 404 means the run id is unknown or has been evicted by newer runs.
    """
    store: dict[str, Any] = getattr(request.app.state, "reports", {})
    report_obj = store.get(run_id)
    if report_obj is None:
        raise HTTPException(status_code=404, detail="Run not found or evicted")

    # The store holds Pydantic FinalReport instances; dump to dict for rendering.
    final_report = report_obj.model_dump() if hasattr(report_obj, "model_dump") else dict(report_obj)

    if format == "json":
        return JSONResponse(
            content=final_report,
            headers={"Content-Disposition": f'attachment; filename="vibeinvest-{run_id}.json"'},
        )

    # format == "md"
    body = _render_markdown(final_report)
    return Response(
        content=body,
        media_type="text/markdown; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="vibeinvest-{run_id}.md"'},
    )
